### ISSUE TITLE
Broken documentation link in README.md

### ISSUE THREAD

**Issue by randycox-eg** [CanopyTax/single-spa-react#28]
In the Quickstart section of README.md, the link to "child app's entry file" is a 404.

**Comment by joeldenning** [comment]
Thanks for reporting this, I fixed it in https://github.com/CanopyTax/single-spa-react/commit/31c04e0fc59cccc014b89320de44f09939a93670. The correct link is https://github.com/CanopyTax/single-spa/blob/master/docs/applications.md#registered-applications
