### ISSUE TITLE
Check for render props and throw errors if they exist

### ISSUE THREAD

**Issue by joeldenning** [CanopyTax/single-spa-react#39]
Parcels do not support passing down render props or react children. This is because parcels are framework agnostic, but render props are React elements. So if the parcel is not written in react, it will not be able to render React elements.

What i'm thinking is that we should check props either in the constructor or in componentDidUpdate (or both) to see if any props are valid react elements. If so, we should throw an error and tell people not to do that.

**Comment by frehner** [comment]
Could use `react-is` for the checking if we wanted to go down that route.

**Comment by joeldenning** [comment]
Closing since this is old.
