### ISSUE TITLE
Parcels are not rendered inline and not "flex"-ible

### ISSUE THREAD

**Issue by courtneynguyen** [CanopyTax/single-spa-react#43]
Parcels do not render inline with content which makes it difficult to style with flexbox. It renders within an extra div that also is not style-able, especially when the Parcel needs to rest flexed/inline with another element.

It would be nice to either:

- Accept `React.Fragment` as a component to wrapWith
- Add a class property to the wrapping div, or perhaps pass style props directly to the wrapping div
- Use react-mount-point-unstable and insert Parcels inline so it can flow naturally

**Comment by frehner** [comment]
Alternatively, `wrapWith` could also be a fragment, right?

**Comment by joeldenning** [comment]
Closing because this is old. Feel free to reopen if there's continued interest in this.
