### ISSUE TITLE
single-spa-react/parcel/index.js doesn't support ie11

### ISSUE THREAD

**Issue by OriLev** [CanopyTax/single-spa-react#47]
although the build of single-spa-react/parcel/index.js goes through 'babel' the following line remains inside the code of index.js:
```  var parcelProps = Object.assign({}, _this.props);```

which causes my app to produce the following error in ie11:

```SCRIPT438: Object doesn't support property of method 'assign'```

any ideas on how can I overcome this hurdle?

**Comment by joeldenning** [comment]
#48 will fix this. In the meantime, you can polyfill `Object.assign` with [es6-object-assign](https://github.com/rubennorte/es6-object-assign)

**Comment by OriLev** [comment]
I checked the solution and it works! thanks a lot for the quick response and fix.

Is there an estimation on the timelines of the release of a version with the fix?

**Comment by joeldenning** [comment]
Released in https://github.com/CanopyTax/single-spa-react/releases/tag/v2.10.1
