### ISSUE TITLE
defaultDomElementGetter not using the same id convention as other helper libs

### ISSUE THREAD

**Issue by tewsonseeoun-toast** [CanopyTax/single-spa-react#51]
single-spa-react has `defaultDomElementGetter()` for creating a DOM element for an app to mount on. `defaultDomElementGetter()` uses the app name as the id of the element. https://github.com/CanopyTax/single-spa-react/blob/v2.10.1/src/single-spa-react.js#L160

However, this behaviour is different from other helper libraries. In other helper libraries, the id is `single-spa-application:${name}`.
- https://github.com/CanopyTax/single-spa-angular/blob/v3.0.0-beta.21/src/browser-lib/single-spa-angular.ts#L150
- https://github.com/CanopyTax/single-spa-vue/blob/master/src/single-spa-vue.js#L55

There might be some benefits in having a consistent pattern of the default DOM element id?

**Comment by joeldenning** [comment]
👍 agreed, let's change single-spa-react to follow that convention.

PR's accepted, or myself or a core team member might be able to get to this in the next day or two.

**Comment by joeldenning** [comment]
Released in https://github.com/CanopyTax/single-spa-react/releases/tag/v2.10.2
