### ISSUE TITLE
Minor bug in defaultDomElementGetter()

### ISSUE THREAD

**Issue by rolandarnoldconga** [CanopyTax/single-spa-react#58]
See defaultDomElementGetter() - https://github.com/CanopyTax/single-spa-react/blob/master/src/single-spa-react.js#L160-L161

`htmlId` will never never be falsey in `if (!htmlId) {`, and should presumably be `if (!props.appName && !props.name) {`

**Comment by joeldenning** [comment]
👍 good catch. This is an easier PR to make - would love a community contribution for this one

**Comment by joeldenning** [comment]
Closed in #59

**Comment by joeldenning** [comment]
Released in https://github.com/CanopyTax/single-spa-react/releases/tag/v2.10.4
