### ISSUE TITLE
Not getting updates on root component

### ISSUE THREAD

**Issue by BartJanvanAssen** [CanopyTax/single-spa-react#61]
Hey, i was just paying around with this project and if i setup this with the Parcel component everything works fine. Whenever i update my custom props then it wont deliver and update / render to my parcel root component.. in #60 you updated the props to the component but can we also get the updates?

so the concept is as follows:

const Application = () => {
   const [currentApp, setCurrentApp] = useState(findAppForPath(window.location.pathname))
  const [customProp, setCustomProp] = useState()
  // const currentParcel = useRef()

  useEffect(() => {
    if (currentApp) {
      // currentParcel.current = MountParcel(currentApp)
      setTimeout(() => {
        setCustomProp({
           test: 'whoo'
        })
      }, 5000)
    }
  }, [currentApp])

return <Parcel 
          mountParcel={mountRootParcel}
          config={currentApp.load}
          handleError={err => console.error(err)}
          customProp1={customProp}
          customProp2='customPropValue2' />
}

So currentApp.load will resolve in a window parcel object like:
window.oneApp = {
  bootstrap,
  mount,
  unmount,
  update: props => {
    customProps = props
    console.log(props) <========= this is being triggered! 
    return Promise.resolve()
  }
}

so the  ======= this is being triggered!  is being triggered only the root component will not receive the updated props..

**Comment by BartJanvanAssen** [comment]
My bad! forgot to add... 

const update = [
  reactLifecycles.update
]

**Comment by joeldenning** [comment]
👍 glad to hear you got it working
